### ISSUE TITLE
Dashboard doesn't show jobs

### ISSUE THREAD

**Issue by ekeric13** [tobymao/saq#58] opened 2023-03-14 01:59 UTC
I am having a lot of trouble getting jobs to show up in the dashboard

<img width="600" alt="Screenshot 2023-03-13 at 6 56 40 PM" src="https://user-images.githubusercontent.com/6489651/224872407-d5dcb892-85b0-4f68-98bb-879204a70293.png">

Here is my setup:
```
class Queue(saq.Queue):
    """[SAQ Queue](https://github.com/tobymao/saq/blob/master/saq/queue.py)

    Configures `orjson` for JSON serialization/deserialization if not otherwise configured.

    Parameters
    ----------
    *args : Any
        Passed through to `saq.Queue.__init__()`
    **kwargs : Any
        Passed through to `saq.Queue.__init__()`
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        kwargs.setdefault("dump", encoder.encode)
        kwargs.setdefault("load", decoder.decode)
        kwargs.setdefault("name", "background-worker")
        super().__init__(*args, **kwargs)

    def namespace(self, key: str) -> str:
        """Make the namespace unique per app."""
        return f"{settings.app.slug}:{self.name}:{key}"


queue = Queue(redis)

...

queue_settings = {
    "queue": queue,
    "concurrency": 10,
}

def start_worker(functions: Collection[WorkerFunction]) -> None:
    global queue_settings
    """

    Args:
        functions: Functions to be called via the async workers.

    Returns:
        The worker instance, instantiated with `functions`.
    """
    # return Worker(queue, functions, concurrency=10)
    # saq.start
    queue_settings["functions"] = functions
    start("app.lib.worker.queue_settings", web=True, port=8080)

```

```
    res = await queue.enqueue(
        "initiate_training",
        data=data,
        key=initiate_training_namespace(order_id),
        timeout=30,
        retries=20,
        retry_delay=5,
        retry_backoff=True,
    )
```

And this is my redis keys:
```
1) "starlite-pg-redis-docker:background-worker:stats:30d27d7c-c20b-11ed-adf6-0242ac130003"
2) "starlite-pg-redis-docker:background-worker:incomplete"
3) "saq:job:background-worker:initiate_training:2c7880db-90a3-4791-baa0-83ace2d0098b"
4) "starlite-pg-redis-docker:background-worker:stats"
5) "starlite-pg-redis-docker:background-worker:schedule"
6) "starlite-pg-redis-docker:background-worker:sweep"
7) "saq:job:background-worker:initiate_training:c673af4b-fcd5-43cc-9c66-36de903e51a6"
```

Do you see anything wrong with what i am doing?

**Comment by tobymao** [comment] 2023-03-14 02:09
seems like you're doing some custom things that could be affecting it. does it work if you don't have any overrides especially with namespace?

**Comment by tobymao** [comment] 2023-03-14 02:11
i'm able to see the ui on latest main, so i don't think this is an issue with saq, but moreso an issue with what you're doing, closing for now, happy to help you debug. my guess is that the issue is with you overriding name space

**Closed by tobymao** 2023-03-14 02:11 UTC

**Comment by ekeric13** [comment] 2023-03-14 02:15
Yeah I am using a modified version of this: https://github.com/starlite-api/starlite-pg-redis-docker/blob/main/app/lib/worker.py 
(wanted to get the web interface working and just doing Worker() didn't seem to support that).

Yeah avoiding the namespace getting overwritten worked!

Also how do I make it so the web ui is only accessible via username password other than env variables?
```
  AUTH_USER     basic auth user, defaults to admin
  AUTH_PASSWORD basic auth password, if not specified, no auth will be used
```

Like can i pass some these values explicitly into `extra_web_settings`?

**Comment by tobymao** [comment] 2023-03-14 02:34
the only way is with env variables at the moment, look at web.py create_app

**Comment by ekeric13** [comment] 2023-03-14 03:38
If a job is continuosly retrying and failing and i realize something is wrong with the associated data, do i just delete the key for that job:
`"saq:job:background-worker:initiate_training:c673af4b-fcd5-43cc-9c66-36de903e51a6"`? or is it more complicated for that.

Essentially the admin UI is great but it is read only. I don't mind having to use the redis-cli for admin actions but I don't know what actions i should take...

**Comment by tobymao** [comment] 2023-03-14 03:46
given a job, you can call abort on it. you can also have a retry limit

**Comment by ekeric13** [comment] 2023-03-14 04:00
Yeah I saw I can call abort on a job but i am talking about after the fact. Like i queue up a job and then an hour later i see in the logs it is failing and the reason it is failing is unrecoverable.
I need to delete that job.
I no longer have a reference to the job I queued as it was from an endpoint that exited.

How would I abort that on going job?

**Comment by tobymao** [comment] 2023-03-14 04:07
you need to keep a reference to jobs if you want to abort it. 
you can get a job by it's id with queue.job(job_key), then you can abort it

**Comment by ekeric13** [comment] 2023-03-15 02:46
Okay created some api endpoints around that.

I am having issues with using a connection pool of redis + saq.

Is there any guidance on the max number of connections needed?

**Comment by tobymao** [comment] 2023-03-15 04:40
well that depends on the number of workers you have. i would imagine that 25 connections with one worker should be enough

**Comment by ekeric13** [comment] 2023-03-15 07:13
Yeah but i am also using redis for other things. Wondering if there is a good way to ballpark it...
